### ISSUE TITLE
Need Update to the new pubmed website!! Thanks!

### ISSUE THREAD

**Issue by smartnikocj** [twlee79/CopyPMID#1]
Hi, thanks you so much for your great job on the tiny button. It helps me a lot! Unfortunately, the Pubmed website have updated the new address (https://pubmed.ncbi.nlm.nih.gov/). Everything is updated, and therefore we can not use the button anymore. I am a new beginner for Python and I know that the button functions according to the website tree. It's difficult for me as a beginner of Python to modify myself. It will be greatly appreciate if you can update the code. Thanks advance. 

Also, please add another copy button for DOI. Nice!

**Comment by smartnikocj** [comment]
The extension have been updated. Thanks a lot for your great contribution.

**Comment by twlee79** [comment]
All good – cheers!
